CREATE DATABASE IF NOT EXISTS `kurator_db`;

USE `kurator_db`;

-- Table: edit_data_points (stores the data points of the edit task)
-- - id: Primary key
-- - username: string
-- - before_edit: The existing configuration
-- - human_change_instruction: The change instruction
-- - after_edit: The new configuration
-- - gpt3_change_instruction: The change instruction generated by GPT-3
-- - notes: The notes of the user
-- - edited: Whether the change instruction was edited by the user
-- - deleted: Whether the change instruction was deleted by the user
-- - created_at: The time when the data point was created
-- - updated_at: The time when the data point was updated
-- - tags: The tags of the data point (json)

CREATE TABLE IF NOT EXISTS edit_data_points (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(255) NOT NULL,
    before_edit TEXT NOT NULL,
    human_change_instruction TEXT NOT NULL,
    after_edit TEXT NOT NULL,
    gpt3_change_instruction TEXT NOT NULL,
    note TEXT NOT NULL,
    edited BOOLEAN NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT False,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tags VARCHAR(10000) NOT NULL DEFAULT '[]'
);
